services:
  acme:
    image: letsencrypt/pebble
    labels:
      envoy.playground.service: "ACME letsencrypt (pebble)"
      envoy.playground.logo: "acme.svg"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    labels:
      envoy.playground.service: "PostgreSQL"
      envoy.playground.logo: "postgres.svg"

  redis:
    image: redis:latest
    labels:
      envoy.playground.service: "Redis"
      envoy.playground.logo: "redis.svg"

  python:
    image: phlax/aiohttp
    labels:
      envoy.playground.service: "Python (asyncio)"
      envoy.playground.logo: "python.png"
      envoy.playground.descriptions: |
        Python/asyncio image with aiohttp and aio-libs
      envoy.playground.config.path: "/code/control/run.py"
      envoy.playground.config.type: "python"
      envoy.playground.config.default: "run.py"
      envoy.playground.config.highlight: "py"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    labels:
      envoy.playground.service: "Jaeger"
      envoy.playground.logo: "jaeger.svg"

  zipkin:
    image: openzipkin/zipkin
    labels:
      envoy.playground.service: "Zipkin"
      envoy.playground.logo: "zipkin.svg"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    labels:
      envoy.playground.service: "Mariadb"
      envoy.playground.logo: "mariadb.svg"

  http-echo:
    image: mendhak/http-https-echo
    labels:
      envoy.playground.service: "HTTP/S echo"
      envoy.playground.logo: "http-echo.svg"
    environment:
      HTTPS_PORT: 0

  solid:
    image: nodesolidserver/node-solid-server
    labels:
      envoy.playground.service: Solid server (node)
      envoy.playground.logo: "solid.svg"
