FROM python:3.8-slim

RUN pip3 install -q \
	aiodocker \
	aiohttp \
	aiohttp_cors \
	pytest-asyncio \
	pytest-cov \
	pytest-flake8 \
	pyyaml
RUN mkdir /code
ADD ./control /code
ENTRYPOINT ["python3", "/code/control/run.py"]
