FROM mhart/alpine-node
WORKDIR /app
RUN apk add --no-cache \
	g++ \
	build-base \
	cairo-dev \
	jpeg-dev \
	pango-dev \
	musl-dev \
	giflib-dev \
	pixman-dev \
	pangomm-dev \
	libjpeg-turbo-dev \
	freetype-dev
CMD ["yarn", "start"]
