version: "3.7"
services:

  control:
    privileged: true
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-control
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../:/code/
    - ../.cache/coverage:/code/coverage
    - ../.cache/control/root/.cache:/root/.cache
    - ../setup.py:/code/setup.py
    - ../services.yaml:/services.yaml
    - ../services:/services
    ports:
    - 8000:8000

  ui:
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-ui
    ports:
    - 8081:3000
    volumes:
    - ../ui:/app
    - ../.cache/coverage:/app/coverage

  docs:
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-docs
    volumes:
    - ../:/code/
    - ../.cache/control/root/.cache:/root/.cache
    - ../services.yaml:/services.yaml
    - ../services:/services
