FROM python:3.8-slim

RUN apt update \
	&& apt install -y --no-install-recommends make curl \
	&& curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash \
	&& export NVM_DIR="$HOME/.nvm" \
	&& [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
        && nvm install 12
RUN mkdir /code
ADD ./playground /code/playground
ADD ./setup.py /code
WORKDIR /code
ENTRYPOINT ["./composition/entrypoint.sh"]
CMD ["playground"]
