version: "2.3"
services:

  control:
    privileged: true
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-control
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../:/code/
    - ../.cache/coverage:/code/coverage
    - ../.cache/control/root/.cache:/root/.cache
    - ../setup.py:/code/setup.py
    - ../services:/services
    ports:
    - 8000:8000
    environment:
      CORS_ALLOWED: http://localhost:5555
      PLAYGROUND_ENV: dev

  ui:
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-ui
    ports:
    - 8081:3000
    volumes:
    - ../ui:/app
    - ../.cache/coverage:/app/coverage

  docs:
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-docs
    volumes:
    - ../:/code/
    - ../.cache/control/root/.cache:/root/.cache
    - ../services:/services

  site:
    build:
      context: ..
      dockerfile: composition/Dockerfile-playground-site
    ports:
    - 8082:3000
    volumes:
    - ../site:/app

  integration:
    privileged: true
    build:
      context: ..
      dockerfile: composition/Dockerfile-in-docker
    working_dir: /code
    volumes:
    - ../bin/integration:/code/bin
    - ../.cache/integration/docker:/var/lib/docker
    - ../tests/integration:/code/tests
    - ../tmp/docker:/tmp/docker

  integration-start:
    image: busybox
    depends_on:
      integration:
        condition: service_healthy
